# Generated by Django 3.0.1 on 2020-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='')),
                ('originalFile', models.ImageField(default='download.png', upload_to='')),
                ('caption', models.CharField(max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default='japneet', max_length=20)),
                ('draft', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
    ]
