# Generated by Django 3.0.1 on 2020-04-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.CharField(default='japneet', max_length=20),
        ),
    ]
