# Generated by Django 3.0.1 on 2020-04-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='originalFile',
            field=models.ImageField(blank=True, default='download.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.CharField(blank=True, default='japneet', max_length=20),
        ),
    ]
