# Generated by Django 3.0.1 on 2020-04-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0002_auto_20200412_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
