# Generated by Django 3.0.1 on 2020-04-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0002_auto_20200414_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.CharField(blank=True, default='japneet', editable=False, max_length=20),
        ),
    ]
