# Generated by Django 3.0.1 on 2020-04-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0003_auto_20200412_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
