# Generated by Django 3.0.1 on 2020-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0003_auto_20200415_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.CharField(blank=True, default='japneet', max_length=20),
        ),
    ]
