# Generated by Django 3.0.1 on 2020-04-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0004_photo_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='draft',
        ),
    ]
