# Generated by Django 3.0.1 on 2020-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0004_auto_20200416_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.CharField(blank=True, default='japneet', editable=False, max_length=20),
        ),
    ]
