# Generated by Django 3.0.1 on 2020-04-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0005_remove_photo_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='originalFile',
            field=models.ImageField(default='media/download.png', upload_to=''),
        ),
    ]
