# Generated by Django 3.0.1 on 2020-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0005_auto_20200416_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.AddField(
            model_name='photo',
            name='presentableFile',
            field=models.ImageField(blank=True, default='download.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='originalFile',
            field=models.ImageField(upload_to=''),
        ),
    ]
