# Generated by Django 3.0.1 on 2020-04-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0006_auto_20200416_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='presentableFile',
            field=models.ImageField(blank=True, default='download.png', editable=False, upload_to=''),
        ),
    ]
