# Generated by Django 3.0.1 on 2020-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofeed', '0007_auto_20200416_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='presentableFile',
            field=models.ImageField(blank=True, editable=False, upload_to=''),
        ),
    ]
